# Generated by Django 4.1.3 on 2022-11-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='category',
            name='source',
        ),
        migrations.AlterField(
            model_name='feed',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='source',
            field=models.ManyToManyField(related_name='categories', to='feed.source'),
        ),
    ]
