# Generated by Django 4.1.3 on 2022-11-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_category_users_category_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='users',
            new_name='user',
        ),
    ]
